apiVersion: v1 
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector: #selector it for label or i can it is an match expression
    app: stdntmgmt-webapp #in service selector should match watever deployment you have created
  ports:
  - port: 8080 #service port
    targetPort: 8080 # container port
